services:
  awesome_api:
    build:
      context: .
      dockerfile: deployments/dev/docker/dockerfile
      target: awesome_api_development_image
    container_name: awesome_api_container
    command: yarn start:debug
    env_file:
      - "./.env"
    volumes:
      - type: bind
        source: .
        target: /awesome-market
    ports:
      - 8700:80
    networks:
      - awesome_network
    restart: always
    profiles:
      - api

  awesome_postgres:
    image: postgres:14-alpine
    container_name: awesome_db_container
    environment:
      POSTGRES_USER: awesome
      POSTGRES_PASSWORD: awesome
      POSTGRES_DB: awesome_development
    volumes:
      - type: volume
        source: postgres_data
        target: /var/lib/postgresql
    ports:
      - 6544:5432
    networks:
      - awesome_network
    restart: always
    profiles:
      - db

networks:
  awesome_network:
    external: true

volumes:
  postgres_data:
    driver: local
